name: IOC Linting
run-name: lint

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        # The following allows for each run step to utilize ~/.bash_profile
        # for setting up the per-step initial state.
        # --login: a login shell. Source ~/.bash_profile
        # -o pipefail: piped processes are important; fail if they fail
        shell: bash --login -o pipefail {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Add the problem matcher
        run: |
          echo "::add-matcher::.github/workflows/matcher.json"   

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install whatrecord
        run: |
          python -m pip install whatrecord

      - name: Parse the startup script
        run: |
          python -m whatrecord parse iocBoot/ioc-test/st.cmd --output-format=json | python support/lint_formatter.py
