name: Trying GitHub actions problem matching
run-name: test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Add the problem matcher
        run: |
          echo "::add-matcher::matcher.json"   
      - name: Make up a problem
        run: |
          echo "iocBoot/ioc-test/st.cmd: line 1, col 1, Error - nonsensical. (no-confusion)"
