name: Trying GitHub actions problem matching
run-name: test
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Add the problem matcher
        run: |
          echo "::add-matcher::.github/workflows/matcher.json"   
      - name: Make up a problem
        run: |
          echo "iocBoot/ioc-test/st.cmd: line 1, col 1, Error - nonsensical - updated. (no-confusion)"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install whatrecord
        run: |
          python -m pip install whatrecord
      - name: Parse the startup script
        run: |
          python -m whatrecord parse iocBoot/ioc-test/st.cmd --output-format=json | python iocBoot/ioc-test/lint_formatter.py
